security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 15

    providers:
        hus_provider:
            memory:
                users:
                    hyorinmaru23:
                        password: $2y$15$3vSVHh0sUZaM1diqGednquQdrZcziIiH7L4ldDS.YvPdfddd9PKpq
                        roles: ROLE_ADMIN
                    s0nnyhu:
                        password: $2y$15$3vSVHh0sUZaM1diqGednquQdrZcziIiH7L4ldDS.YvPdfddd9PKpq
                        roles: ROLE_ADMIN
                    contact@husonny.fr:
                        password: $2y$15$3vSVHh0sUZaM1diqGednquQdrZcziIiH7L4ldDS.YvPdfddd9PKpq
                        roles: ROLE_ADMIN
                    husonny1@gmail.com:
                        password: $2y$15$3vSVHh0sUZaM1diqGednquQdrZcziIiH7L4ldDS.YvPdfddd9PKpq
                        roles: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: user
                password_parameter: pwd
                default_target_path: admin
            logout:
                path: logout
                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
